version: "3"
services:
  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 123.com
      MYSQL_ROOT_HOST: '%'
  web:
    build: .
    restart: always
    ports:
      - 8080:8080